### ISSUE TITLE
Error getting validation data

### ISSUE THREAD

**Issue by JC-ironman** [JonasAlfredsson/docker-nginx-certbot#195]
Hi, I'm a bit stuck on using the docker compose. 

My docker compose:

---

```yml
version: "3.8"
services:
  api:
    [...]
    
  frontend:
    [...]
  
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: <container-name>
    restart: unless-stopped
    env_file:
      - <env file>
    ports:
      - 23456:80 # I need this to be custom
      - 34567:443 # I need this to be custom
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/dev:/etc/nginx/user_conf.d

volumes:
  nginx_secrets: {}
```

---

env file
```
CERTBOT_EMAIL=<my email>
```

---

./nginx/dev/nginx.conf
```
# nginx.conf
upstream backend {
    server api:3000;
}

upstream admin {
    server frontend;
}

server {
    listen 80;

    server_name <domain>;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name <domain>;

    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_protocols TLSv1.2;

    include mime.types;
    charset utf-8;
    client_max_body_size 512M;
    keepalive_timeout  0;

    location / {
        proxy_pass http://admin/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    location /api {
        proxy_pass http://backend/api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
```

---

I know that my domain is well set up. Got an error and I don't succeed to fix it

```
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: <domain>
  Type:   connection
  Detail: <ip>: Fetching http://<domain>/.well-known/acme-challenge/[...]: Error getting validation data

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
```

If you could help me it would be great !
