### ISSUE TITLE
Standard nginx "docker-entrypoint.sh" not being used

### ISSUE THREAD

**Issue by captain828** [JonasAlfredsson/docker-nginx-certbot#221]
`docker-entrypoint.sh` is never executed by default.

One effect of this is the lack of `/docker-entrypoint.d/20-envsubst-on-templates.sh` from also being executed automatically, which converts templates with env vars.

Obvs not a big deal just not sure if this was intentional or not :)

**Comment by JonasAlfredsson** [comment]
Hi captain828,

I am not sure how you start the image, but for me it sure looks like the entrypoint scirpt executes?

```
docker run -it -e CERTBOT_EMAIL=test -e USE_LOCAL_CA=1 -e DEBUG=1 jonasal/nginx-certbot:latest

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/12/21 10:37:40 [debug] Debug messages are enabled
```

**Comment by captain828** [comment]
I am using docker-compose and passing an environment file for the entire compose script (extra services removed for brevity).
```
services:
  nginx:
      image: jonasal/nginx-certbot:latest-alpine
      restart: unless-stopped
      environment:
        - CERTBOT_EMAIL=${CERTBOT_EMAIL}
        - APP_DOMAIN=${APP_DOMAIN}
        - APP_HOST=${APP_HOST}
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./nginx/app.conf:/etc/nginx/templates/app.conf
        - ./nginx/envar_substitution.sh:/docker-entrypoint.d/envar_substitution.sh
        - ./nginx/static:/var/www/app/static
      command: >
        sh -cx "chmod +x /docker-entrypoint.d/envar_substitution.sh &&
                /scripts/start_nginx_certbot.sh"

volumes:
  nginx:
    driver: local
```

Where `envar_substitution.sh` is:
```
#!/bin/sh

export APP_DOMAIN
export APP_HOST

envsubst '${APP_DOMAIN},${APP_HOST}' < /etc/nginx/templates/app.conf > /etc/nginx/user_conf.d/app.conf

exec "$@"
```
