### ISSUE TITLE
Unable to enable specific ciphers

### ISSUE THREAD

**Issue by ivanvaccari** [JonasAlfredsson/docker-nginx-certbot#247]
I need to enable a specific ciphers for Tls v1.2 wich is used by an old system to connect to our service via nginx as reverse proxy.

The deault ssl configuration don't let the service connect and give us a generic "ssl handshake failed". After some research i found out i need to enable the **AES128-GCM-SHA256** cipher, but despite adding it to the nginx.conf file, which the gets mounted in the image, nginx won't use it.

Using ssllabs.com tool the cipher suite i get is the following one:
![image](https://github.com/JonasAlfredsson/docker-nginx-certbot/assets/28731723/6d433759-f51a-487c-bd10-18d7cda070ea)

which does not include the needed cipher.

- I'm using the debian 5.01 image.
- openssl ciphers -s shows it in list.

I'm getting a bit lost online searching for various infos, it looks like that if:
- openssl supports it (which it does, checked with "openssl ciphers")
- nginx.conf defines it in "ssl_ciphers" string 
- 
Then it sould appear and be available. But it's not.

An older setup (nginx directly installed in the host, not via docker) from which the config was copy-pasted does allow the usage, as confirmed via ssllabs tool:
![image](https://github.com/JonasAlfredsson/docker-nginx-certbot/assets/28731723/c2e22e0d-e3fb-4888-a5e3-174b5cd80a24)

There's something about it i need to know?

**Comment by JonasAlfredsson** [comment]
Hi ivanvaccari, 

Can you post your nginx.conf file and explain how you mount it into the container.

On a `server` level you can define ciphers like in this example: https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/examples/example_server_multicert.conf

**Comment by ivanvaccari** [comment]
Hi, this is is the nginx.config in use:

```user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;
        client_max_body_size 16M;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings. See https://ssl-config.mozilla.org/#server=nginx
        ##
        ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:le_nginx_SSL:10m;
        ssl_session_timeout 1440m;
        ssl_session_tickets off;
        # Updated list: https://ssl-config.mozilla.org/#server=nginx
        ssl_ciphers TLS_RSA_WITH_AES_128_GCM_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;

        ##
        # Logging Settings
        ##
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##
        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

The needed cipher is **TLS_RSA_WITH_AES_128_GCM_SHA256** (https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_GCM_SHA256/)

The compose configuration used to launch the instance:
```
version: '3.7'
services:
  nginx:
    image: jonasal/nginx-certbot:5.0.1
    volumes:
    - ./nginx/maintenance:/var/www/maintenance
    - ./nginx/maintenancemode:/etc/nginx/maintenancemode
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf     # volume per config nginx
    - ./nginx/templates:/etc/nginx/templates
    - ./letsencrypt:/etc/letsencrypt # volume per certbot. Necessario solo se si usa immagine jonasal/nginx-certbot
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host 
    environment:
    - NGINX_HOST=***************
    - CERTBOT_EMAIL=*****************
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

```
