### ISSUE TITLE
Unable to renew certificates

### ISSUE THREAD

**Issue by Kesuera** [JonasAlfredsson/docker-nginx-certbot#262]
Hello,

first of all thanks for your work. I have been using this docker image multiple times and had no problem so far. However I can't seem to get my head around this one.

When I run docker compose up for the first time I always get this error:

```sh
nginx  | 2024/06/18 17:10:37 [info] Starting certificate renewal process
nginx  | 2024/06/18 17:10:37 [info] Requesting an ECDSA certificate for '<domain>' (http-01 through webroot)
nginx  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx  | Account registered.
nginx  | Requesting a certificate for <domain>
nginx  |
nginx  | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
nginx  |   Domain: <domain>
nginx  |   Type:   unauthorized
nginx  |   Detail: 2a00:4b40:aaaa:2009::6: Invalid response from http://<domain>/.well-known/acme-challenge/P2vSMN9tf-HfFwtJW62Ol6fCa0d9I6aFYSVGb1wuFNI: 404
nginx  |
nginx  | Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
```

When I manually create a `test.txt` file in `/var/www/letsencrypt/.well-known/acme-challenge/` and try to request it by url: `http://<domain>/.well-known/acme-challenge/test.txt` the response is correct and I can see my file. But it seems that there is no file created when requesting the certificate.

I have no idea what's wrong. It was always working for me.

My configurations are:

`docker-compose.yaml`

```yaml
networks:
  <network>:
    driver: bridge
    name: <network>

services:
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: "<email>"
      CERTBOT_DOMAIN: "<domain>"
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    networks:
      - <network>

volumes:
  nginx_secrets:
    name: nginx_secrets
```

`user_conf.d/app.conf`

```sh
server {
    listen 80 http2 default_server reuseport;
    listen [::]:80 http2 default_server reuseport;

    server_name <domain>;
    server_tokens off;

    location '/.well-known/acme-challenge' {
        default_type "text/plain";
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://$http_host$request_uri;
    }
}

server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl http2 default_server reuseport;
    listen [::]:443 ssl http2 default_server reuseport;

    server_name <domain>;

    # Load the certificate files.
    ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/<domain>/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    # Strict-Transport-Security
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;

    location / {
      root /var/www/frontend/current;
      index index.html;
      try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }
}
```

Thanks for your response
