### ISSUE TITLE
Passing through environment variables to nginx

### ISSUE THREAD

**Issue by tudddorrr** [JonasAlfredsson/docker-nginx-certbot#64]
The official nginx image lets you pass in environment variables from compose to nginx so that they can be used in your conf file.

I'm not really sure where to go because the official image wants you to use template files whereas this setup is very specific with symlinking config files.

This is kind of what i was going for:
```
  web:
    image: jonasal/nginx-certbot:2.4.0-alpine
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=blah@blah.com
      - SERVER_NAME=api.blah.com
      - BACKEND_PORT=3000
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/letsencrypt
      - ./config/nginx:/etc/nginx/user_conf.d
```

And then in the conf file:
```
server {
    listen              443 ssl default_server;
    server_name         ${SERVER_NAME};

    location / {
        proxy_pass http://backend:${BACKEND_PORT};
    }
}
```
