### ISSUE TITLE
Important file(s) are missing, disabling...

### ISSUE THREAD

**Issue by CorrM** [JonasAlfredsson/docker-nginx-certbot#99]
hello, did u have any idea why i get that error

```
// api.conf
limit_req_zone $binary_remote_addr zone=apiLimit:10m rate=16r/s;

server {
    location / {
        limit_req zone=apiLimit burst=20 nodelay;

        proxy_pass         http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name api.localhost;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/api.cheatgear/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/api.cheatgear/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/api.cheatgear/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;
}
```

```ini
// nginx-cerbot.env
# Required
CERTBOT_EMAIL=MY_EMAIL@gmail.com

# Optional (Defaults)
DHPARAM_SIZE=2048
ELLIPTIC_CURVE=secp256r1
RENEWAL_INTERVAL=8d
RSA_KEY_SIZE=2048
STAGING=1
USE_ECDSA=0

# Advanced (Defaults)
CERTBOT_AUTHENTICATOR=webroot
CERTBOT_DNS_PROPAGATION_SECONDS=""
DEBUG=1
USE_LOCAL_CA=0
```

```yml
version: "3.9"
services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    expose:
      - "5000"
    volumes:
      - ./docker/api/data:/var/lib/cheat-gear

  nginx:
    container_name: webserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    environment:
      - STAGING=1
      - DEBUG=1
    env_file:
      - ./docker/nginx/nginx-certbot.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./docker/nginx/configs:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:

```

```
Debug messages are enabled
Creating symlinks to any files found in /etc/nginx/user_conf.d/
Creating symlink '/etc/nginx/conf.d/api.conf' to '/etc/nginx/user_conf.d/api.conf'
Creating symlink '/etc/nginx/conf.d/cheat_gear.conf' to '/etc/nginx/user_conf.d/cheat_gear.conf'
Creating symlink '/etc/nginx/conf.d/docs.conf' to '/etc/nginx/user_conf.d/docs.conf'
Could not find keyfile file '/etc/letsencrypt/live/api.cheatgear/privkey.pem' in '/etc/nginx/conf.d/api.conf'
Could not find fullchain file '/etc/letsencrypt/live/api.cheatgear/fullchain.pem' in '/etc/nginx/conf.d/api.conf'
Could not find chain file '/etc/letsencrypt/live/api.cheatgear/chain.pem' in '/etc/nginx/conf.d/api.conf'
Could not find keyfile file '/etc/letsencrypt/live/cheatgear/privkey.pem' in '/etc/nginx/conf.d/cheat_gear.conf'
Could not find fullchain file '/etc/letsencrypt/live/cheatgear/fullchain.pem' in '/etc/nginx/conf.d/cheat_gear.conf'
Could not find chain file '/etc/letsencrypt/live/cheatgear/chain.pem' in '/etc/nginx/conf.d/cheat_gear.conf'
Could not find keyfile file '/etc/letsencrypt/live/docs.cheatgear/privkey.pem' in '/etc/nginx/conf.d/docs.conf'
Could not find fullchain file '/etc/letsencrypt/live/docs.cheatgear/fullchain.pem' in '/etc/nginx/conf.d/docs.conf'
Could not find chain file '/etc/letsencrypt/live/docs.cheatgear/chain.pem' in '/etc/nginx/conf.d/docs.conf'
Starting the Nginx service in debug mode
Starting the autorenewal service
Creating symlinks to any files found in /etc/nginx/user_conf.d/
Important file(s) for '/etc/nginx/conf.d/api.conf' are missing, disabling...
Important file(s) for '/etc/nginx/conf.d/cheat_gear.conf' are missing, disabling...
Important file(s) for '/etc/nginx/conf.d/docs.conf' are missing, disabling...
```

and that's by proj struct if would help
![image](https://user-images.githubusercontent.com/5868825/148063518-b2b61dd4-f898-4511-8db1-b770b008d32a.png)
